#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 27 15:27:46 2019

@author: william
"""

import math
import numpy as np

def create_grid(sudokuArray):
    cellArray = []
    sectionNumbers = [ [] for t in range(9)]
    for i in range(sudokuArray.shape[0]):
        cellArray.append([])
        for j in range(sudokuArray.shape[1]):
            cellArray[i].append(Cell(i,j))
        if sudokuArray[i][j] != None:
            cellArray[i][j].assignNumber(sudokuArray[i][j],sectionNumbers)
            
    return cellArray,sectionNumbers

x, y = create_grid(trainingSudoku)







#print(x[0][0].possibleNumbers)
#print('finished') 
#print(y[2])
#print('..........')
#a = 0
#while all(len(s) != 9 for s in y):
#    a += 1
#    print('lap {}...............................'.format(a))
#    for i in range(9):
#        for j in range(9):
#            print('pre assigned number: ' + str(x[i][j].assignedNumber))
#            print('pre possible number: ' + str(x[i][j].possibleNumbers))
#            if x[i][j].assignedNumber == None:
#                x[i][j].updatePossibleNumbers(trainingSudoku,y)
#            print('assigned number: ' + str(x[i][j].assignedNumber))
#            print('possible number: ' + str(x[i][j].possibleNumbers))
#            print('................')
#            print(a)
#    if a > 100:
#        print('iteration100')
#        break​
