#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May  3 21:21:31 2019

@author: william
"""
import numpy as np

crossTestingSudoku1 = np.array([
    [None,4,1,None,None,None,2,5,None],
    [6,None,None,2,4,5,None,None,None],
    [None,None,None,6,None,None,None,None,3],
    [None,7,None,None,2,8,None,6,9],
    [None,2,9,None,None,None,8,1,None],
    [8,1,None,9,3,None,None,2,None],
    [4,None,None,None,None,1,None,None,None],
    [None,None,None,8,5,3,None,None,2],
    [None,5,3,None,None,None,6,7,None]
       ])


crossTestingSudoku2 = np.array([
    [8,None,None,None,None,None,1,None,None],
    [None,None,3,4,5,None,None,9,None],
    [4,9,6,None,None,1,2,None,None],
    [None,None,1,7,3,None,None,None,None],
    [5,4,None,1,None,2,None,8,3],
    [None,None,None,None,8,4,7,None,None],
    [None,None,4,3,None,None,9,6,2],
    [None,3,None,None,6,7,5,None,None],
    [None,None,2,None,None,None,None,None,8]
      ])



trainingSudoku = np.array([
    [None,None,None,2,6,None,7,None,1],
    [6,8,None,None,7,None,None,9,None],
    [1,9,None,None,None,4,5,None,None],
    [8,2,None,1,None,None,None,4,None],
    [None,None,4,6,None,2,9,None,None],
    [None,5,None,None,None,3,None,2,8],
    [None,None,9,3,None,None,None,7,4],
    [None,4,None,None,5,None,None,3,6],
    [7,None,3,None,1,8,None,None,None]
      ])

trainingSudokuSolution = np.array([
    [4,3,5,2,6,9,7,8,1],
    [6,8,2,5,7,1,4,9,3],
    [1,9,7,8,3,4,5,6,2],
    [8,2,6,1,9,5,3,4,7],
    [3,7,4,6,8,2,9,1,5],
    [9,5,1,7,4,3,6,2,8],
    [5,1,9,3,2,6,8,7,4],
    [2,4,8,9,5,7,1,3,6],
    [7,6,3,4,1,8,2,5,9]
        ])
